In [8]:
import pandas as pd 
import numpy as np 
from pathlib import Path 
print("Libraries loaded successfully")

Libraries loaded successfully

In [9]:
file_path = "../data/cleaned/paimana_all_months_combined.csv" 
df = pd.read_csv(file_path) 
print("Dataset loaded successfully") 
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully
Rows: 7594
Columns: 18

In [10]:
pd.set_option("display.max_columns", None) 
df.head()

,MINISTRY,SECTOR,SL.NO,PROJECT NAME,AGENCY,PROJECT CODE(S),STATE,DATE OF APPROVAL,START DATE,ORIGINAL/TARGET DOC,REVISED DOC,ORIGINAL COST (RS. CRORE),REVISED COST (RS. CRORE),CUMULATIVE EXPENDITURE (RS. CRORE),PHYSICAL PROGRESS (%),SOURCE PAGE,REPORT MONTH,SOURCE FILE
0,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1714.0,"AMENDED BHARATNET PROGRAM - KTK, GOA, PY",DEPARTMENT OF TELECOMMUNICATIONS,108841 | - | -,PAN INDIA,Aug-23,Jun-25,Jun-28,-,3742.0,3742.0,435.31,0.0815,149.0,JULY,Project_Monitoring_July_2026.xlsx
1,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1800.0,"AMENDED BHARATNET PROGRAM - KTK, GOA, PY",DEPARTMENT OF TELECOMMUNICATIONS,108841 | - | -,PAN INDIA,Aug-23,Jun-25,Jun-28,-,3742.0,3742.0,435.31,0.0000,157.0,JUNE,Project_Monitoring_June_2026.xlsx
2,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1715.0,AMENDED BHARATNET PROGRAM - HR,DEPARTMENT OF TELECOMMUNICATIONS,124199 | - | -,PAN INDIA,Aug-23,Mar-26,Mar-29,-,837.0,837.0,83.68,0.0000,149.0,JULY,Project_Monitoring_July_2026.xlsx
3,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1716.0,AMENDED BHARATNET PROGRAM - PB,DEPARTMENT OF TELECOMMUNICATIONS,171218 | - | -,PAN INDIA,Aug-23,Feb-25,Feb-28,-,1245.0,1245.0,0.00,0.2658,149.0,JULY,Project_Monitoring_July_2026.xlsx
4,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1717.0,"AMENDED BHARATNET PROGRAM - MP, DD AND DNH",DEPARTMENT OF TELECOMMUNICATIONS,175860 | - | -,PAN INDIA,Jun-23,May-25,May-28,-,4943.0,4943.0,562.13,0.0840,149.0,JULY,Project_Monitoring_July_2026.xlsx

In [11]:
print("All columns:\n") 
for i, column in enumerate(df.columns, 1):    
    print(i, "→", column)

All columns:

1 → MINISTRY
2 → SECTOR
3 → SL.NO
4 → PROJECT NAME
5 → AGENCY
6 → PROJECT CODE(S)
7 → STATE
8 → DATE OF APPROVAL
9 → START DATE
10 → ORIGINAL/TARGET DOC
11 → REVISED DOC
12 → ORIGINAL COST (RS. CRORE)
13 → REVISED COST (RS. CRORE)
14 → CUMULATIVE EXPENDITURE (RS. CRORE)
15 → PHYSICAL PROGRESS (%)
16 → SOURCE PAGE
17 → REPORT MONTH
18 → SOURCE FILE

In [12]:
df.columns = (    
    df.columns    
    .str.strip()    
    .str.upper()    
    .str.replace(" ", "_")    
    .str.replace("/", "_", regex=False)    
    .str.replace("(", "", regex=False)    
    .str.replace(")", "", regex=False)    
    .str.replace("%", "PCT", regex=False)    
    .str.replace(".", "", regex=False) 
)

In [13]:
missing = pd.DataFrame({    
    "Missing_Count": df.isna().sum(),    
    "Missing_Percentage": (        
        df.isna().mean() * 100 )
        .round(2) }) 
missing = missing.sort_values(    "Missing_Percentage",    ascending=False ) 
missing

                                 Missing_Count  Missing_Percentage
DATE_OF_APPROVAL                            68                0.90
START_DATE                                  15                0.20
REVISED_DOC                                 15                0.20
SECTOR                                       4                0.05
ORIGINAL_TARGET_DOC                          4                0.05
SLNO                                         4                0.05
PROJECT_CODES                                4                0.05
AGENCY                                       4                0.05
STATE                                        4                0.05
PROJECT_NAME                                 4                0.05
SOURCE_PAGE                                  4                0.05
REPORT_MONTH                                 4                0.05
PHYSICAL_PROGRESS_PCT                        4                0.05
MINISTRY                                     0                0.00
CUMULATIVE_EXPENDITURE_RS_CRORE              0                0.00
REVISED_COST_RS_CRORE                        0                0.00
ORIGINAL_COST_RS_CRORE                       0                0.00
SOURCE_FILE                                  0                0.00

In [14]:
duplicate_rows = df.duplicated().sum() 
print("Exact duplicate rows:", duplicate_rows)

Exact duplicate rows: 0

In [15]:
[col for col in df.columns if "PROJECT_CODE" in col]

['PROJECT_CODES']

In [16]:
PROJECT_ID = "PROJECT_CODES" 
print("Unique project codes:") 
print(df[PROJECT_ID].nunique())

Unique project codes:
3580

In [17]:
print(df["REPORT_MONTH"].value_counts() )

REPORT_MONTH
MAY      1987
APRIL    1981
JUNE     1847
JULY     1775
Name: count, dtype: int64

In [18]:
print(df.columns.tolist())

['MINISTRY', 'SECTOR', 'SLNO', 'PROJECT_NAME', 'AGENCY', 'PROJECT_CODES', 'STATE', 'DATE_OF_APPROVAL', 'START_DATE', 'ORIGINAL_TARGET_DOC', 'REVISED_DOC', 'ORIGINAL_COST_RS_CRORE', 'REVISED_COST_RS_CRORE', 'CUMULATIVE_EXPENDITURE_RS_CRORE', 'PHYSICAL_PROGRESS_PCT', 'SOURCE_PAGE', 'REPORT_MONTH', 'SOURCE_FILE']

In [19]:
date_columns = [    
    col for col in df.columns    
    if "DATE" in col or "DOC" in col ] 
print(date_columns)

['DATE_OF_APPROVAL', 'START_DATE', 'ORIGINAL_TARGET_DOC', 'REVISED_DOC']

In [20]:
for col in date_columns:    
    df[col] = pd.to_datetime(        
        df[col],
         errors="coerce"    
    ) 
print("Date conversion completed")

Date conversion completed

C:\Users\commu\AppData\Local\Temp\ipykernel_6668\2116691869.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(
C:\Users\commu\AppData\Local\Temp\ipykernel_6668\2116691869.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(
C:\Users\commu\AppData\Local\Temp\ipykernel_6668\2116691869.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(
C:\Users\commu\AppData\Local\Temp\ipykernel_6668\2116691869.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(

In [21]:
numeric_keywords = [    "COST",    "EXPENDITURE",    "PROGRESS" ] 
numeric_columns = [    
    col for col in df.columns    
    if any(word in col for word in numeric_keywords) ] 
print(numeric_columns)

['ORIGINAL_COST_RS_CRORE', 'REVISED_COST_RS_CRORE', 'CUMULATIVE_EXPENDITURE_RS_CRORE', 'PHYSICAL_PROGRESS_PCT']

In [22]:
for col in numeric_columns:    
    df[col] = (        
        df[col]        
        .astype(str)        
        .str.replace(",", "", regex=False)        
        .str.replace("₹", "", regex=False)        
        .str.strip()    )        
        
    df[col] = pd.to_numeric(
         df[col],        
         errors="coerce"    ) 
         
print("Numerical conversion completed")

Numerical conversion completed

In [23]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
ORIGINAL_COST_RS_CRORE,7594.0,3780.417685,82515.547734,102.4,355.9925,795.18000,1527.0000,3712662.01
REVISED_COST_RS_CRORE,7594.0,4291.038019,93818.004807,0.1,358.3000,796.97000,1661.2500,4278402.37
CUMULATIVE_EXPENDITURE_RS_CRORE,7594.0,2196.616750,48157.095093,0.0,54.2625,249.53500,728.7025,2196663.55
PHYSICAL_PROGRESS_PCT,7590.0,0.595984,0.345616,0.0,0.2800,0.68215,0.9230,1.00

In [24]:
progress_col = "PHYSICAL_PROGRESS_PCT"
print("Minimum:", df[progress_col].min()) 
print("Maximum:", df[progress_col].max())
print("Median:", df[progress_col].median())

Minimum: 0.0
Maximum: 1.0
Median: 0.68215

In [25]:
# part B 
df["PHYSICAL_PROGRESS_PERCENT"] = (df[progress_col] * 100)
df[    [        progress_col,        "PHYSICAL_PROGRESS_PERCENT"    ] ].head(20)

    PHYSICAL_PROGRESS_PCT  PHYSICAL_PROGRESS_PERCENT
0                  0.0815                       8.15
1                  0.0000                       0.00
2                  0.0000                       0.00
3                  0.2658                      26.58
4                  0.0840                       8.40
5                  0.1513                      15.13
6                  0.0765                       7.65
7                  0.0000                       0.00
8                  0.0000                       0.00
9                  0.0179                       1.79
10                 0.0002                       0.02
11                 0.0000                       0.00
12                 0.1872                      18.72
13                 0.9990                      99.90
14                 0.4400                      44.00
15                 0.4000                      40.00
16                 0.3800                      38.00
17                 0.4000                      40.00
18                 0.8800                      88.00
19                 0.8340                      83.40

In [26]:
# PART C - STANDARDIZE REPORT MONTH

df["REPORT_MONTH"] = (
    df["REPORT_MONTH"] 
    .astype(str)
    .str.strip()
    .str.upper()
)

# Correct month order
month_order = [
    "APRIL",
    "MAY",
    "JUNE",
    "JULY"
]

df["REPORT_MONTH"] = pd.Categorical(
    df["REPORT_MONTH"],
    categories=month_order,
    ordered=True
)

print("Report month standardized successfully!")
print(df["REPORT_MONTH"].value_counts())

Report month standardized successfully!
REPORT_MONTH
MAY      1987
APRIL    1981
JUNE     1847
JULY     1775
Name: count, dtype: int64

In [27]:
# PART d 

df = df.sort_values(    [PROJECT_ID, "REPORT_MONTH"] ) 
df.head(20)

,MINISTRY,SECTOR,SLNO,PROJECT_NAME,AGENCY,PROJECT_CODES,STATE,DATE_OF_APPROVAL,START_DATE,ORIGINAL_TARGET_DOC,REVISED_DOC,ORIGINAL_COST_RS_CRORE,REVISED_COST_RS_CRORE,CUMULATIVE_EXPENDITURE_RS_CRORE,PHYSICAL_PROGRESS_PCT,SOURCE_PAGE,REPORT_MONTH,SOURCE_FILE,PHYSICAL_PROGRESS_PERCENT
1,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1800.0,"AMENDED BHARATNET PROGRAM - KTK, GOA, PY",DEPARTMENT OF TELECOMMUNICATIONS,108841 | - | -,PAN INDIA,1-08-23,1-06-25,1-06-28,NaT,3742.00,3742.00,435.31,0.0000,157.0,JUNE,Project_Monitoring_June_2026.xlsx,0.00
0,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1714.0,"AMENDED BHARATNET PROGRAM - KTK, GOA, PY",DEPARTMENT OF TELECOMMUNICATIONS,108841 | - | -,PAN INDIA,1-08-23,1-06-25,1-06-28,NaT,3742.00,3742.00,435.31,0.0815,149.0,JULY,Project_Monitoring_July_2026.xlsx,8.15
2,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1715.0,AMENDED BHARATNET PROGRAM - HR,DEPARTMENT OF TELECOMMUNICATIONS,124199 | - | -,PAN INDIA,1-08-23,1-03-26,1-03-29,NaT,837.00,837.00,83.68,0.0000,149.0,JULY,Project_Monitoring_July_2026.xlsx,0.00
3,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1716.0,AMENDED BHARATNET PROGRAM - PB,DEPARTMENT OF TELECOMMUNICATIONS,171218 | - | -,PAN INDIA,1-08-23,1-02-25,1-02-28,NaT,1245.00,1245.00,0.00,0.2658,149.0,JULY,Project_Monitoring_July_2026.xlsx,26.58
4,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1717.0,"AMENDED BHARATNET PROGRAM - MP, DD AND DNH",DEPARTMENT OF TELECOMMUNICATIONS,175860 | - | -,PAN INDIA,1-06-23,1-05-25,1-05-28,NaT,4943.00,4943.00,562.13,0.0840,149.0,JULY,Project_Monitoring_July_2026.xlsx,8.40
5,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1718.0,AMENDED BHARATNET PROGRAM - WB & ANI,DEPARTMENT OF TELECOMMUNICATIONS,210914 | - | -,PAN INDIA,1-08-23,1-02-25,1-02-28,NaT,1674.00,1674.00,223.41,0.1513,149.0,JULY,Project_Monitoring_July_2026.xlsx,15.13
7,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1806.0,AMENDED BHARATNET PROGRAM - UP (EAST),DEPARTMENT OF TELECOMMUNICATIONS,222253 | - | -,UTTAR PRADESH,1-08-23,1-02-25,1-02-28,NaT,5008.00,5008.00,502.00,0.0000,158.0,JUNE,Project_Monitoring_June_2026.xlsx,0.00
6,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1736.0,AMENDED BHARATNET PROGRAM - UP (EAST),DEPARTMENT OF TELECOMMUNICATIONS,222253 | - | -,UTTAR PRADESH,1-08-23,1-02-25,1-02-28,NaT,5008.00,5008.00,502.00,0.0765,150.0,JULY,Project_Monitoring_July_2026.xlsx,7.65
8,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1719.0,AMENDED BHARATNET PROGRAM - AS,DEPARTMENT OF TELECOMMUNICATIONS,240484 | - | -,PAN INDIA,1-08-23,1-03-26,1-03-29,NaT,832.00,832.00,83.16,0.0000,149.0,JULY,Project_Monitoring_July_2026.xlsx,0.00
9,MINISTRY OF HOUSING & URBAN AFFAIRS,URBAN PUBLIC TRANSPORT,272.0,JAIPUR METRO RAIL PROJECT PHASE 2 (PRAHLADPURA...,JAIPUR METRO RAIL CORPORATION,245986 | - | -,RAJASTHAN,1-04-26,1-04-26,1-10-31,NaT,13037.66,13037.66,1.79,0.0179,68.0,JULY,Project_Monitoring_July_2026.xlsx,1.79
10,MINISTRY OF POWER,ELECTRICITY GENERATION,175.0,"MEJA THERMAL POWER PROJECT, STAGE-II , (3X800 MW)",NATIONAL THERMAL POWER CORPORATION [NTPC],298178 | - | -,UTTAR PRADESH,1-06-26,1-06-26,2032-12-01,NaT,38358.00,38358.00,1002.73,0.0002,63.0,JULY,Project_Monitoring_July_2026.xlsx,0.02
11,DEPARTMENT OF TELECOMMUNICATIONS,TELECOMMUNICATION,1720.0,AMENDED BHARATNET PROGRAM - OD,DEPARTMENT OF TELECOMMUNICATIONS,317725 | - | -,PAN INDIA,1-08-23,1-07-26,1-07-29,NaT,1713.00,1713.00,0.00,0.0000,149.0,JULY,Project_Monitoring_July_2026.xlsx,0.00
12,MINISTRY OF STEEL,STEEL,516.0,STAMP CHARGE BATTERY NO.12 BY-PRODUCT PLANT AT...,STEEL AUTHORITY OF INDIA LIMITED (SAIL,364934 | - | -,WEST BENGAL,1-01-25,1-02-25,1-07-28,NaT,999.46,999.46,70.37,0.1872,80.0,JULY,Project_Monitoring_July_2026.xlsx,18.72
13,MINISTRY OF POWER,TRANSMISSION & DISTRIBUTION,232.0,TRANSMISSION NETWORK EXPANSION IN GUJARAT TO I...,POWER GRID CORPORATION OF INDIA LIMITED [POWER...,400005 | N18000337 | 4690,MULTI-STATES (DADRA & NAGAR HAVELI AND DAMAN &...,1-01-22,1-07-22,1-06-23,1-05-26,4546.26,4546.26,4528.07,0.9990,66.0,APRIL,Project_Monitoring_April_2026.xlsx,99.90
15,MINISTRY OF RAILWAYS,RAILWAYS,699.0,JHARSUGUDA-BARPALI-SARDEGA PH II WORKS- RAIL C...,SOUTH EASTERN RAILWAY [SER] - I,400006 | - | -,ODISHA,1-10-21,1-10-21,1-10-25,1-12-26,808.99,808.99,743.46,0.4000,92.0,JUNE,Project_Monitoring_June_2026.xlsx,40.00
14,MINISTRY OF RAILWAYS,RAILWAYS,662.0,JHARSUGUDA-BARPALI-SARDEGA PH II WORKS- RAIL C...,SOUTH EASTERN RAILWAY [SER] - I,400006 | - | -,ODISHA,1-10-21,1-10-21,1-10-25,1-12-26,808.99,808.99,743.46,0.4400,87.0,JULY,Project_Monitoring_July_2026.xlsx,44.00
16,MINISTRY OF RAILWAYS,RAILWAYS,711.0,JHARSUGUDA-BARPALI-SARDEGA PH II WORKS- RAIL C...,SOUTH EASTERN RAILWAY [SER] - I,400006 | - | 4689,ODISHA,1-10-21,1-10-21,1-10-25,1-12-26,808.99,808.99,701.15,0.3800,89.0,APRIL,Project_Monitoring_April_2026.xlsx,38.00
17,MINISTRY OF RAILWAYS,RAILWAYS,713.0,JHARSUGUDA-BARPALI-SARDEGA PH II WORKS- RAIL C...,SOUTH EASTERN RAILWAY [SER] - I,400006 | - | 4689,ODISHA,1-10-21,1-10-21,1-10-25,1-12-26,808.99,808.99,743.46,0.4000,88.0,MAY,Project_Monitoring_May_2026.xlsx,40.00
19,MINISTRY OF CIVIL AVIATION,AVIATION & AVIATION INFRASTRUCTURE,14.0,CONSTRUCTION OF TERMINAL BUILDING & ASSOCIATED...,AIRPORT AUTHORITY OF INDIA [AAI],400010 | - | -,LADAKH,1-07-18,1-09-18,1-09-21,1-07-26,480.00,640.00,509.41,0.8340,59.0,JUNE,Project_Monitoring_June_2026.xlsx,83.40
18,MINISTRY OF CIVIL AVIATION,AVIATION & AVIATION INFRASTRUCTURE,14.0,CONSTRUCTION OF TERMINAL BUILDING & ASSOCIATED...,AIRPORT AUTHORITY OF INDIA [AAI],400010 | - | -,LADAKH,1-07-18,1-09-18,1-09-21,1-07-26,480.00,640.00,512.55,0.8800,55.0,JULY,Project_Monitoring_July_2026.xlsx,88.00

In [28]:
project_month_count = (    
    df.groupby(PROJECT_ID)["REPORT_MONTH"]    
    .nunique()    
    .sort_values(ascending=False)
)
print(project_month_count.value_counts())

REPORT_MONTH
2    3072
4     280
1     179
3      49
Name: count, dtype: int64

In [29]:
projects_4_months = project_month_count[    
    project_month_count == 4 ] 
print(    "Projects appearing in all 4 months:",    len(projects_4_months) )

Projects appearing in all 4 months: 280

In [30]:
output_path = "../data/cleaned/paimana_cleaned.csv" 
df.to_csv(    output_path,    index=False ) 
print("Cleaned dataset saved to:") 
print(output_path)

Cleaned dataset saved to:
../data/cleaned/paimana_cleaned.csv